version: "3.7"

services:
  redis:
    container_name: redis-for-data-structures-with-kotlin
    image: redis:7.0.8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-for-data-structures-with-kotlin-volume:/data
    networks:
      - redis-for-data-structures-with-kotlin-network

  redis-commander:
    container_name: redis-commander-for-data-structures-with-kotlin
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    environment:
      REDIS_HOSTS: redis
    ports:
      - "6381:8081"
    networks:
      - redis-for-data-structures-with-kotlin-network

volumes:
  redis-for-data-structures-with-kotlin-volume:

networks:
  redis-for-data-structures-with-kotlin-network:
    name: redis-for-data-structures-with-kotlin
